name: isolated_bloc
description: "Support for running blocs in an isolate."
version: 1.1.0
repository: https://github.com/kocherovets/isolated_bloc.git

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: